const { validateResult } = require('../helpers/validationHelper')

const { validateParam, validateName, validateString, validateLength, validateNumber, validateBoolean, validateEmail } = require('./validations')

const validationEmpleado = [
    validateParam('numero_identificacion'),
    validateNumber('numero_identificacion'),
    validateLength('numero_identificacion', {min:6, max:20}),
    validateParam('nombres'),
    validateName('nombres'),
    validateLength('nombres', {min:3, max:25}),
    validateParam('apellidos'),
    validateName('apellidos'),
    validateLength('apellidos', {min:3, max:25}),
    validateParam('genero'),
    validateBoolean('genero'),
    validateParam('fecha_nacimiento'),
    validateParam('lugar_nacimiento_fk'),
    validateParam('fecha_expedicion_doc'),
    validateParam('lugar_exp_doc_fk'),
    validateParam('nacionalidad_fk'),
    validateParam('estado_civil_fk'),
    validateParam('centro_costo_fk'),
    validateParam('lugar_trabajo_fk'),
    validateParam('cargo_fk'),
    validateParam('tipo_contrato_fk'),
    validateParam('tipo_tiempo_fk'),
    validateParam('fecha_ingreso'),
    validateParam('jefe_directo_fk'),
    validateParam('estado_contrato_fk'),
    validateParam('salario_fk'),
    validateParam('aux_movilidad_fk'),
    validateParam('correo_electronico'),
    validateEmail('correo_electronico'),
    validateLength('correo_electronico', {min:5, max:50}),
    validateParam('direccion'),
    validateLength('direccion', {min:5, max:50}),
    validateParam('telefono_fijo'),
    validateLength('telefono_fijo', {min:3, max:20}),
    validateParam('celular'),
    validateNumber('celular'),
    validateLength('celular', {min:5, max:20}),
    validateParam('estudios_fk'),
    validateParam('banco_fk'),
    validateParam('tipo_cuenta_fk'),
    validateParam('num_cuenta'),
    validateNumber('num_cuenta'),
    validateLength('num_cuenta', {min:5, max:20}),
    validateParam('eps_fk'),
    validateParam('arl_fk'),
    validateParam('riesgo'),
    validateNumber('riesgo'),
    validateParam('pension_fk'),
    validateParam('cesantias_fk'),
    validateParam('ccf_fk'),
    validateParam('contacto_emergencia'),
    validateName('contacto_emergencia'),
    validateLength('contacto_emergencia', {min:3, max:30}),
    validateParam('tel_contacto_emergencia'),
    validateLength('tel_contacto_emergencia', {min:3, max:20}),
    validateParam('talla_camisa_fk'),
    validateParam('talla_pantalon_fk'),
    validateParam('talla_calzado_fk'),
    validateParam('empresa_fk'),
    (req,res,next)=>validateResult(req,res,next)
]

module.exports = { validationEmpleado }